### ISSUE TITLE
HTTP Connection errors not reported by WriteStreamSubscriberImpl

### ISSUE THREAD

**Issue by laurentvaills** [vert-x3/vertx-rx#242] opened 2021-01-04 11:53 UTC
### Version

Vert.x Reactive 3.9.5

### Context

I tried to connect the HTTP client to a non listening host or port and the error is not reported with the `WriteStreamSubscriber` while it was with the plain `WriteStream` `exceptionHandler`.

### Do you have a reproducer?

Here is a github project with a reproducer: 
* https://github.com/laurentvaills/vertx-rx-connection-error-3.9

You can see the issue with `TestVertxHttpClientReactive`. 

### Extra

* macOS 10.15.7
* JVM openjdk version "11.0.9.1" 2020-11-04

### Investigation

It seems that the problem is due to Vert.x doing the connection lazily. 
It waits for having enough bytes to send to initiate the connection. But if not enough bytes were sent before ending the request, then the connection error that is reported can't be relayed through the errors handlers that the `done` flag was already set. 
If the request contains few bytes (as you can see in the reproducer), then the error is correctly reported through the `onWriteStreamError`.
So maybe the implementation of `onComplete` should not set the `done` first, but just checking it is already done or not, then call the `writeStream.end` and finally set the done flag.

**Comment by tsegismont** [comment] 2021-02-22 10:41
@laurentvaills thanks for reporting the issue and your findings. Closing this one as duplicate of #188 (we use issue labels to generate the release notes).

**Closed by tsegismont** 2021-02-22 10:41 UTC
Labels: duplicate
