### ISSUE TITLE
Upgrade rxjava to 2.0

### ISSUE THREAD

**Issue by tramonex-yilin** [vert-x3/vertx-rx#56] opened 2016-10-31 09:55 UTC
Newest stable version of rxjava is `2.0`.

**Comment by vietj** [comment] 2016-10-31 09:59
there is currently a branch with rxjava 2

**Comment by vietj** [comment] 2016-10-31 09:59
https://github.com/vert-x3/vertx-rx/tree/rxjava2

**Comment by pmlopes** [comment] 2016-11-01 11:42
Duplicate of: vert-x3/issues#189

**Closed** 2016-11-01 11:42 UTC
Labels: duplicate
