### ISSUE TITLE
Vert.x Junit test does not complete using Rxjava 

### ISSUE THREAD

**Issue by RobWin** [vert-x3/vertx-rx#91] opened 2017-04-15 10:36 UTC
Please See https://github.com/eclipse/vert.x/issues/1941

**Comment by tsegismont** [comment] 2018-11-13 20:48
Closing not a bug, see https://github.com/eclipse-vertx/vert.x/issues/1941#issuecomment-438431089

**Closed by tsegismont** 2018-11-13 20:48 UTC
Labels: invalid
