### ISSUE TITLE
Errors not passed to logging framework

### ISSUE THREAD

**Issue by pendula95** [vert-x3/vertx-rx#199] opened 2019-06-05 10:07 UTC
Unhadeled errors don't get propagated to logging framework.
Reproducer: https://github.com/pendula95/vertx-logger-reproducer
Version: 3.7.1

`mvn clean package`
`java -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.SLF4JLogDelegateFactory -jar target/logger-1.0.0-SNAPSHOT-fat.jar`
`curl -v 127.0.0.1:8888`
Inspect testFile.log and you will notice no error is logged.

**Comment by pendula95** [comment] 2019-06-05 21:59
I added one more test example. Previous example results in 500 server error. New example results in request never completing and in the end timeouting. 
New usage:
curl -v 127.0.0.1:8888/test1
curl -v 127.0.0.1:8888/test2

**Comment by tsegismont** [comment] 2019-06-06 08:30
@pendula95 in my testing, I changed the config to log to CONSOLE for simplicity

```xml
<configuration scan="true">
    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
        <append>true</append>
        <encoder>
            <charset>UTF-8</charset>
            <pattern>%d %-4relative [%thread] %-5level %logger{128} - %msg%n</pattern>
        </encoder>
    </appender>

    <root level="INFO">
        <appender-ref ref="CONSOLE"/>
    </root>
</configuration>
```

You can't see the exception when sending a request to `/test1` because by default Vert.x Web does not show failures in route handler code. You must add a failure handler:

```java
    router.get("/test1").handler(routingContext -> {
      routingContext.response().putHeader("content-type", "application/json").end(Json.encode(testDTO));
    }).failureHandler(routingContext -> {
      logger.error("Failure", routingContext.failure());
      routingContext.response().setStatusCode(500).end();
    });
```

Then for `/test2`, the error is logged as per you `RxJavaPlugins` config. The timeout is expected: the corresponding response is never completed. There are a couple of ways to deal with this:

1/ add a timeout handler to the route to reduce the default timeout
2/ revisit you Rx stream definition so that as much operation as possible are in the pipeline instead of the subscriber callbacks

If you do this, then any uncaught exception will be passed to the subscriber error handler. That will give you the opportunity to log the error and terminate the exchange properly. Here's an example:

```java
    router.get("/test2").handler(rc -> {
      Maybe.just(testDTO)
        .map(Json::encodePrettily)
        .subscribe(json -> ok(rc, json), throwable -> internalError(rc, throwable), () -> notFound(rc));
    });
```

This will give you the error in a JSON response as expected.

Side note: in the example above I've removed all the `Maybe`/`Single<Optional>` conversions. `Maybe` is very well suited to deal with optional values and it won't create extra garbage.

**Comment by tsegismont** [comment] 2019-06-06 08:32
Closing as not a bug but feel free to continue the conversation if you need more details.

**Closed by tsegismont** 2019-06-06 08:32 UTC
